// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwpgqrmcubxgmbzsrdbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3cGdxcm1jdWJ4Z21ienNyZGJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MjIzNzMsImV4cCI6MjA2NzQ5ODM3M30.WhJ5B3XcLMYlbZZgzUDH35gp4rmPYb2AByV5GWxC1l4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});